name: pytorch_env
channels:
  - nvidia
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - numpy=1.24.3
  - pytorch=2.0.0  # Or the latest compatible version
  - torchvision=0.15.0  # Adjust to the compatible version with PyTorch
  - torchaudio=2.0.0  # Adjust to the compatible version with PyTorch
  - pytorch-cuda=11.8
  - ipykernel
  - matplotlib 
